host: "localhost"
port: 8080
crt_path: "secret/ok_server.crt"
key_path: "secret/ok_server.key"
rabbit:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "emails"
  exchange_type: "direct"
  queue: "user_emails"
redis:
  url: "localhost:6379"
  password: ""
access_token_dur_minutes: 15
rate_limit_per_second: 10
