name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Create .env file for cadv_api
        run: |
          echo "CURRENCY_URL=${{ secrets.CURRENCY_URL }}" >> build/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> build/.env
          echo "HOST=${{ secrets.HOST }}" >> build/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> build/.env
          echo "SECRT_REFRESH_KEY=${{ secrets.SECRT_REFRESH_KEY }}" >> build/.env
      
      - name: Create secret folder and add certificates
        run: |
          mkdir -p secret
          echo "${{ secrets.TEST_SERVER_SECRET_CRT }}" > secret/ok_server.crt
          echo "${{ secrets.TEST_SERVER_SECRET_KEY }}" > secret/ok_server.key
          echo "${{ secrets.TEST_SERVER_SECRET_CSR }}" > secret/ok_server.csr
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build&Push
        run: |
          docker build -f build/dockerfile -t cashadvisorbeta/cadv_api:latest .
          docker push cashadvisorbeta/cadv_api:latest